# -*- coding: utf-8 -*-
"""Infinity APK Builder [Simple].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13AE8RvjnCfuBJGaACEqxeBIMo33_l-Sc

## This Script downloads the current version of Infinity-For-Reddit and compiles it to an APK.

Follow the instructions (if any) and then just run the code snippets one after the other. \
You don't have to touch the code at all. \
(When I say API token or API key, I mean the same thing.)

**Please consider donating to the author Docile Alligator [here](https://patreon.com/docile_alligator)!**

Thanks to all contributors (u/hostilenemy, u/Oha_der_erste, u/StudyGuidex, u/aman207) keeping this Notebook alive!

FAQ at the end of this Notebook.
"""

# Commented out IPython magic to ensure Python compatibility.
#@title 1. Setup the environment
#@markdown 1. Create the API application [here](https://old.reddit.com/prefs/apps/) with the following settings: \
#@markdown - name: **`{YourRedditUsername}s-app`** (Replace {YourRedditUsername} with your actual username) \
#@markdown - type: **`Installed app`** \
#@markdown - redirect uri: **`http://127.0.0.1`** \
#@markdown Example: \
#@markdown ![](https://i.ibb.co/HVGrc8M/grafik.png) \
#@markdown The API token is then shown at the bottom of the page under the App name  ("{YourRedditUsername}s-app") and is a set of random characters (e.g. 6g5ZHEGEAnKHP3vewUFY3y) \
#@markdown Input the **API token** and **your username** below and go to 2. \
api_token = 'MklS0TZ6zFHBZ98e0B8pUA' #@param {type:"string"}
your_reddit_username = 'RevaFloyd' #@param {type:"string"}
user_agent = f"android:personal-app:0.0.1 (by /u/{your_reddit_username})"
redirect_uri = 'http://127.0.0.1'


#@markdown \
#@markdown 2. Choose where to download the source code from (Standard: GitHub Repository) \
#@markdown If GitHub Repository fails, run Code block 4. and choose [GitHub Archive]
version = '[GitHub Repository]' #@param ["[GitHub Repository]", "[GitHub Archive]"]

#@markdown \
#@markdown 3. Run the snippet on the top left. \
#@markdown This will set up the environment to compile the .apk from. \
#@markdown This can take up to 3 minutes.

import os, sys, re

if not api_token or not your_reddit_username:
  print("")
  print("\x1b[31m[IMPORTANT]")
  print("No settings have been set. Please input your token and username.\x1b[0m")
  sys.exit()
else:
  print("Following settings have been set:")
  print("- User-Agent:", user_agent)
  print("- API token:", api_token)
  print("- Source location:", version)



#2. Update the VM, install JDK 11, Android SDK and setup sdkmanager (Just click run, don't make any cli inputs)
!apt-get --quiet update
!apt-get --quiet install openjdk-17-jdk
!wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
!unzip -q android-sdk.zip -d android-sdk

os.environ["ANDROID_SDK_ROOT"] = "/content/android-sdk"
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-17-openjdk-amd64"
os.environ["PATH"] += ":/content/android-sdk/tools/bin:/content/android-sdk/platform-tools"

# setup sdkmanager
!yes | /content/android-sdk/cmdline-tools/bin/sdkmanager  --sdk_root=$ANDROID_SDK_ROOT "platforms;android-30" "build-tools;30.0.3"


#3. Download the source code
if version == "[GitHub Repository]":
  !git clone "https://github.com/Docile-Alligator/Infinity-For-Reddit"
else:
  !wget "https://github.com/Docile-Alligator/Infinity-For-Reddit/archive/a46e96f3e48a89f7b683fa7308c39f01c5b5ac21.zip"
  !unzip "a46e96f3e48a89f7b683fa7308c39f01c5b5ac21.zip"
  !mv -T Infinity-For-Reddit-* Infinity-For-Reddit
# %cd Infinity-For-Reddit/




#4. Change the API token, user agent and Redirect URI to yours and add keystore (Just click run)
# Change API
apiutils_file = "/content/Infinity-For-Reddit/app/src/main/java/ml/docilealligator/infinityforreddit/utils/APIUtils.java"

apiutils_code = open(apiutils_file, "r", encoding="utf-8-sig").read()
apiutils_code = apiutils_code.replace("NOe2iKrPPzwscA", api_token)
apiutils_code = apiutils_code.replace("infinity://localhost", redirect_uri)
apiutils_code = re.sub(r'public static final String USER_AGENT = ".*?";', f'public static final String USER_AGENT = "{user_agent}";', apiutils_code)

with open(apiutils_file, "w", encoding="utf-8") as f:
  f.write(apiutils_code)


# Add Keystore
# Is this written any good? No? I know
!wget -P /content/ "https://github.com/TanukiAI/Infinity-keystore/raw/main/Infinity.jks"

build_gradle_file = "/content/Infinity-For-Reddit/app/build.gradle"
build_gradle_code = open(build_gradle_file, "r", encoding="utf-8-sig").read()
build_gradle_code = build_gradle_code.replace(r"""    buildTypes {""", r"""    signingConfigs {
        release {
            storeFile file("/content/Infinity.jks")
            storePassword "Infinity"
            keyAlias "Infinity"
            keyPassword "Infinity"
        }
    }
    buildTypes {""")
build_gradle_code = build_gradle_code.replace(r"""    buildTypes {
        release {""", r"""    buildTypes {
        release {
            signingConfig signingConfigs.release""")
build_gradle_code = build_gradle_code.replace(r"""    lint {
        disable 'MissingTranslation'
    }""", r"""    lint {
        disable 'MissingTranslation'
        baseline = file("lint-baseline.xml")
    }""")

with open(build_gradle_file, "w", encoding="utf-8") as f:
  f.write(build_gradle_code)

#@title 2. Build the APK. This can take up to 15 minutes. (Just click run)
if not api_token or not your_reddit_username:
  print("")
  print("\x1b[31m[IMPORTANT]")
  print("No settings have been set. Please input your token and username in Step 1.\x1b[0m")
  sys.exit()
!./gradlew updateLintBaseline
!./gradlew assembleRelease

#@title 3. Download the APK directly or via Catbox.moe or file.io
#@markdown If you do this on a **phone**, choose **[.apk Direct Download]** for direct .apk download. \
#@markdown If you do this on a **computer**, choose **[Upload to file.io ...]** and it will upload it to file.io and show a QR code which will link you to the download page. \
#@markdown \
#@markdown Of course you can do [.apk Direct Download] on your computer and transfer the .apk file manually to your phone.
dl = '[.apk Direct Download]' #@param ["[.apk Direct Download]", "[Upload to Catbox.moe and create and show a QR code]", "[Upload to file.io and create and show QR code]"]

import os

if not os.path.exists("/content/Infinity.apk"):
  !mv /content/Infinity-For-Reddit/app/build/outputs/apk/release/app*.apk /content/Infinity.apk


if dl == "[.apk Direct Download]":
  from google.colab import files
  files.download('/content/Infinity.apk')
else:
  !pip install requests pyqrcode pypng
  from IPython.display import clear_output, Image, display
  import pyqrcode
  import requests

  clear_output()
  dl_url = None

  # Set Upload URL
  if "Catbox" in dl:
    url = "https://litterbox.catbox.moe/resources/internals/api.php"
    files = {
      'fileToUpload': ('Infinity.apk', open('/content/Infinity.apk', 'rb')),
      'time': (None, '12h'),
      'reqtype': (None, 'fileupload')
    }
    dl_url = requests.post(url, files=files).text
  else:
    url = 'https://file.io'

    # Upload
    with open("/content/Infinity.apk", 'rb') as file:
      files = {'file': file}
      response = requests.post(url, files=files).json()

    ## Check if upload failed
    if response["success"]:
      dl_url = response["link"]

  if dl_url is None:
    print("Error uploading. Use another download method.")

  else:
    # Generate and display QR code
    qr = pyqrcode.create(dl_url)
    img = "myqr.png"
    qr.png(img, scale=10)
    Image(img)
    print("Download URL:", dl_url)
    display(Image(img))

#@title 4. Delete the current Google Colab VM (after you have downloaded the .apk, THIS STEP IS INTENDED TO FAIL!)
from google.colab import runtime
runtime.unassign()

"""# FAQ

**Q**: How do I install an .apk file on my phone? \
**A**: First you need to transfer the .apk file to your phone (e.g. via Cable, Google Drive, WeTransfer, etc.) \
Then you need to open the .apk file with a file manager and install

**Q**: Does this work with other apps (Sync, Boost, etc.) or on an Apple phone/tablet? \
**A**: Unfortunately, no.

**Q**: It says "Build failed" in red. What do I do? \
**A**: Post a comment on the [Reddit post](https://www.reddit.com/r/Infinity_For_Reddit/comments/14c2v5x/build_your_own_apk_with_your_personal_api_key_in/).

**Q**: When I try to log in, it gives me an "Oauth" error. \
**A**: Uninstall the app again and recreate a new .apk file with a new API. \
Be sure to input the redirect URI correctly like when creating the API key. \
Just look at the example.

**Q**: How do I check if it uses my API? \
**A**: After you have logged in, you have to authorize the API key. \
That's when you can see the name of your API key.

**Q**: How do I update the app? \
**A**: Create an .apk file with the same API key as before and just install the .apk file. \
No need for uninstalling if you've had already installed an .apk file from here before.

**Q**: I have another question/problem? \
**A**: Post it in this [Reddit post](https://www.reddit.com/r/Infinity_For_Reddit/comments/14c2v5x/build_your_own_apk_with_your_personal_api_key_in/).

**Q**: I can't install the app even though I uninstalled the old app. \
("App not installed as package conflicts with an existing package.") \
**A**: Maybe the app is still is in your Secure Folder or installed as an virtual/dual app. You'd have to uninstall that, too, for it to work.

**Q**: Can I add more accounts? \
**A**: The API key is not bound to your account, rather to you personally. You can add as much accounts as you like.

**Q**: I keep getting an .apk.zip or .apk.txt file. \
**A**: Remove the .zip or .txt file extension so the name of the file ends with .apk
"""